# Generated by Django 5.2.8 on 2025-11-24 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_name', models.CharField(max_length=20)),
                ('car_model', models.CharField(max_length=20)),
                ('car_id', models.IntegerField()),
                ('car_colour', models.CharField(max_length=20)),
            ],
        ),
    ]
